---
- name: create_directory
  hosts: all
  become_user: ubuntu
  gather_facts: False
  tasks:
  - name: Install apache httpd but avoid starting it immediately (state=present is optional)
    apt:
       name: apache2
       state: present
    environment:
       RUNLEVEL: 1
